### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/landmapper#45]
- [x] get content for home page
- [x] fix modal login
- [x] anonymous workflow
- [x] tax lot selection
- [x] add tax lot later
- [x] add soils layer
- [x] add streams layer
- [x] get legends
- [x] print CSS
- [x] social logins
- [x] account profile page
- [x] add donate button
- [x] #44 
- [x] #42 
- [x] #35 
- [x] #39 
- [x] #20 
- [x] #21 
- [x] #22 
- [x] #26 
- [ ] #27 
- [x] #14 
- [x] #6 
- [x] #3 
- [x] #5

**Comment by pollardld** [comment]
block for mapnik installation. https://github.com/rhodges/EFH_UTF_SERVER  
no UWSGI in /etc/

**Comment by pollardld** [comment]
data can be found at https://viewer.nationalmap.gov/services/
